global:
  application_name: my-node-app
  default_region: ap-south-1
  platform: Node.js

branch-defaults:
  main:
    environment: My-node-app-env
  my-feature-branch: # optional, for dev previews
    environment: my-node-app-staging
